[package]
name = "nyro-limit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { version = "1", features = ["sync"] }
thiserror.workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "test-util"] }
