// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/nyroway/nyro/go/internal/storage/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newConsumerRoute(db *gorm.DB, opts ...gen.DOOption) consumerRoute {
	_consumerRoute := consumerRoute{}

	_consumerRoute.consumerRouteDo.UseDB(db, opts...)
	_consumerRoute.consumerRouteDo.UseModel(&model.ConsumerRoute{})

	tableName := _consumerRoute.consumerRouteDo.TableName()
	_consumerRoute.ALL = field.NewAsterisk(tableName)
	_consumerRoute.ConsumerID = field.NewString(tableName, "consumer_id")
	_consumerRoute.RouteID = field.NewString(tableName, "route_id")

	_consumerRoute.fillFieldMap()

	return _consumerRoute
}

type consumerRoute struct {
	consumerRouteDo consumerRouteDo

	ALL        field.Asterisk
	ConsumerID field.String
	RouteID    field.String

	fieldMap map[string]field.Expr
}

func (c consumerRoute) Table(newTableName string) *consumerRoute {
	c.consumerRouteDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c consumerRoute) As(alias string) *consumerRoute {
	c.consumerRouteDo.DO = *(c.consumerRouteDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *consumerRoute) updateTableName(table string) *consumerRoute {
	c.ALL = field.NewAsterisk(table)
	c.ConsumerID = field.NewString(table, "consumer_id")
	c.RouteID = field.NewString(table, "route_id")

	c.fillFieldMap()

	return c
}

func (c *consumerRoute) WithContext(ctx context.Context) IConsumerRouteDo {
	return c.consumerRouteDo.WithContext(ctx)
}

func (c consumerRoute) TableName() string { return c.consumerRouteDo.TableName() }

func (c consumerRoute) Alias() string { return c.consumerRouteDo.Alias() }

func (c consumerRoute) Columns(cols ...field.Expr) gen.Columns {
	return c.consumerRouteDo.Columns(cols...)
}

func (c *consumerRoute) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *consumerRoute) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 2)
	c.fieldMap["consumer_id"] = c.ConsumerID
	c.fieldMap["route_id"] = c.RouteID
}

func (c consumerRoute) clone(db *gorm.DB) consumerRoute {
	c.consumerRouteDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c consumerRoute) replaceDB(db *gorm.DB) consumerRoute {
	c.consumerRouteDo.ReplaceDB(db)
	return c
}

type consumerRouteDo struct{ gen.DO }

type IConsumerRouteDo interface {
	gen.SubQuery
	Debug() IConsumerRouteDo
	WithContext(ctx context.Context) IConsumerRouteDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IConsumerRouteDo
	WriteDB() IConsumerRouteDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IConsumerRouteDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IConsumerRouteDo
	Not(conds ...gen.Condition) IConsumerRouteDo
	Or(conds ...gen.Condition) IConsumerRouteDo
	Select(conds ...field.Expr) IConsumerRouteDo
	Where(conds ...gen.Condition) IConsumerRouteDo
	Order(conds ...field.Expr) IConsumerRouteDo
	Distinct(cols ...field.Expr) IConsumerRouteDo
	Omit(cols ...field.Expr) IConsumerRouteDo
	Join(table schema.Tabler, on ...field.Expr) IConsumerRouteDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IConsumerRouteDo
	RightJoin(table schema.Tabler, on ...field.Expr) IConsumerRouteDo
	Group(cols ...field.Expr) IConsumerRouteDo
	Having(conds ...gen.Condition) IConsumerRouteDo
	Limit(limit int) IConsumerRouteDo
	Offset(offset int) IConsumerRouteDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IConsumerRouteDo
	Unscoped() IConsumerRouteDo
	Create(values ...*model.ConsumerRoute) error
	CreateInBatches(values []*model.ConsumerRoute, batchSize int) error
	Save(values ...*model.ConsumerRoute) error
	First() (*model.ConsumerRoute, error)
	Take() (*model.ConsumerRoute, error)
	Last() (*model.ConsumerRoute, error)
	Find() ([]*model.ConsumerRoute, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConsumerRoute, err error)
	FindInBatches(result *[]*model.ConsumerRoute, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ConsumerRoute) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IConsumerRouteDo
	Assign(attrs ...field.AssignExpr) IConsumerRouteDo
	Joins(fields ...field.RelationField) IConsumerRouteDo
	Preload(fields ...field.RelationField) IConsumerRouteDo
	FirstOrInit() (*model.ConsumerRoute, error)
	FirstOrCreate() (*model.ConsumerRoute, error)
	FindByPage(offset int, limit int) (result []*model.ConsumerRoute, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IConsumerRouteDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c consumerRouteDo) Debug() IConsumerRouteDo {
	return c.withDO(c.DO.Debug())
}

func (c consumerRouteDo) WithContext(ctx context.Context) IConsumerRouteDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c consumerRouteDo) ReadDB() IConsumerRouteDo {
	return c.Clauses(dbresolver.Read)
}

func (c consumerRouteDo) WriteDB() IConsumerRouteDo {
	return c.Clauses(dbresolver.Write)
}

func (c consumerRouteDo) Session(config *gorm.Session) IConsumerRouteDo {
	return c.withDO(c.DO.Session(config))
}

func (c consumerRouteDo) Clauses(conds ...clause.Expression) IConsumerRouteDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c consumerRouteDo) Returning(value interface{}, columns ...string) IConsumerRouteDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c consumerRouteDo) Not(conds ...gen.Condition) IConsumerRouteDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c consumerRouteDo) Or(conds ...gen.Condition) IConsumerRouteDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c consumerRouteDo) Select(conds ...field.Expr) IConsumerRouteDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c consumerRouteDo) Where(conds ...gen.Condition) IConsumerRouteDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c consumerRouteDo) Order(conds ...field.Expr) IConsumerRouteDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c consumerRouteDo) Distinct(cols ...field.Expr) IConsumerRouteDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c consumerRouteDo) Omit(cols ...field.Expr) IConsumerRouteDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c consumerRouteDo) Join(table schema.Tabler, on ...field.Expr) IConsumerRouteDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c consumerRouteDo) LeftJoin(table schema.Tabler, on ...field.Expr) IConsumerRouteDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c consumerRouteDo) RightJoin(table schema.Tabler, on ...field.Expr) IConsumerRouteDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c consumerRouteDo) Group(cols ...field.Expr) IConsumerRouteDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c consumerRouteDo) Having(conds ...gen.Condition) IConsumerRouteDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c consumerRouteDo) Limit(limit int) IConsumerRouteDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c consumerRouteDo) Offset(offset int) IConsumerRouteDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c consumerRouteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IConsumerRouteDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c consumerRouteDo) Unscoped() IConsumerRouteDo {
	return c.withDO(c.DO.Unscoped())
}

func (c consumerRouteDo) Create(values ...*model.ConsumerRoute) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c consumerRouteDo) CreateInBatches(values []*model.ConsumerRoute, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c consumerRouteDo) Save(values ...*model.ConsumerRoute) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c consumerRouteDo) First() (*model.ConsumerRoute, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerRoute), nil
	}
}

func (c consumerRouteDo) Take() (*model.ConsumerRoute, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerRoute), nil
	}
}

func (c consumerRouteDo) Last() (*model.ConsumerRoute, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerRoute), nil
	}
}

func (c consumerRouteDo) Find() ([]*model.ConsumerRoute, error) {
	result, err := c.DO.Find()
	return result.([]*model.ConsumerRoute), err
}

func (c consumerRouteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ConsumerRoute, err error) {
	buf := make([]*model.ConsumerRoute, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c consumerRouteDo) FindInBatches(result *[]*model.ConsumerRoute, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c consumerRouteDo) Attrs(attrs ...field.AssignExpr) IConsumerRouteDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c consumerRouteDo) Assign(attrs ...field.AssignExpr) IConsumerRouteDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c consumerRouteDo) Joins(fields ...field.RelationField) IConsumerRouteDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c consumerRouteDo) Preload(fields ...field.RelationField) IConsumerRouteDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c consumerRouteDo) FirstOrInit() (*model.ConsumerRoute, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerRoute), nil
	}
}

func (c consumerRouteDo) FirstOrCreate() (*model.ConsumerRoute, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ConsumerRoute), nil
	}
}

func (c consumerRouteDo) FindByPage(offset int, limit int) (result []*model.ConsumerRoute, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c consumerRouteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c consumerRouteDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c consumerRouteDo) Delete(models ...*model.ConsumerRoute) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *consumerRouteDo) withDO(do gen.Dao) *consumerRouteDo {
	c.DO = *do.(*gen.DO)
	return c
}
