// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	Consumer      *consumer
	ConsumerKey   *consumerKey
	ConsumerQuota *consumerQuota
	ConsumerRoute *consumerRoute
	Route         *route
	RouteUpstream *routeUpstream
	Setting       *setting
	Upstream      *upstream
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Consumer = &Q.Consumer
	ConsumerKey = &Q.ConsumerKey
	ConsumerQuota = &Q.ConsumerQuota
	ConsumerRoute = &Q.ConsumerRoute
	Route = &Q.Route
	RouteUpstream = &Q.RouteUpstream
	Setting = &Q.Setting
	Upstream = &Q.Upstream
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		Consumer:      newConsumer(db, opts...),
		ConsumerKey:   newConsumerKey(db, opts...),
		ConsumerQuota: newConsumerQuota(db, opts...),
		ConsumerRoute: newConsumerRoute(db, opts...),
		Route:         newRoute(db, opts...),
		RouteUpstream: newRouteUpstream(db, opts...),
		Setting:       newSetting(db, opts...),
		Upstream:      newUpstream(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Consumer      consumer
	ConsumerKey   consumerKey
	ConsumerQuota consumerQuota
	ConsumerRoute consumerRoute
	Route         route
	RouteUpstream routeUpstream
	Setting       setting
	Upstream      upstream
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Consumer:      q.Consumer.clone(db),
		ConsumerKey:   q.ConsumerKey.clone(db),
		ConsumerQuota: q.ConsumerQuota.clone(db),
		ConsumerRoute: q.ConsumerRoute.clone(db),
		Route:         q.Route.clone(db),
		RouteUpstream: q.RouteUpstream.clone(db),
		Setting:       q.Setting.clone(db),
		Upstream:      q.Upstream.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Consumer:      q.Consumer.replaceDB(db),
		ConsumerKey:   q.ConsumerKey.replaceDB(db),
		ConsumerQuota: q.ConsumerQuota.replaceDB(db),
		ConsumerRoute: q.ConsumerRoute.replaceDB(db),
		Route:         q.Route.replaceDB(db),
		RouteUpstream: q.RouteUpstream.replaceDB(db),
		Setting:       q.Setting.replaceDB(db),
		Upstream:      q.Upstream.replaceDB(db),
	}
}

type queryCtx struct {
	Consumer      IConsumerDo
	ConsumerKey   IConsumerKeyDo
	ConsumerQuota IConsumerQuotaDo
	ConsumerRoute IConsumerRouteDo
	Route         IRouteDo
	RouteUpstream IRouteUpstreamDo
	Setting       ISettingDo
	Upstream      IUpstreamDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Consumer:      q.Consumer.WithContext(ctx),
		ConsumerKey:   q.ConsumerKey.WithContext(ctx),
		ConsumerQuota: q.ConsumerQuota.WithContext(ctx),
		ConsumerRoute: q.ConsumerRoute.WithContext(ctx),
		Route:         q.Route.WithContext(ctx),
		RouteUpstream: q.RouteUpstream.WithContext(ctx),
		Setting:       q.Setting.WithContext(ctx),
		Upstream:      q.Upstream.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
