// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/nyroway/nyro/go/internal/storage/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newRouteUpstream(db *gorm.DB, opts ...gen.DOOption) routeUpstream {
	_routeUpstream := routeUpstream{}

	_routeUpstream.routeUpstreamDo.UseDB(db, opts...)
	_routeUpstream.routeUpstreamDo.UseModel(&model.RouteUpstream{})

	tableName := _routeUpstream.routeUpstreamDo.TableName()
	_routeUpstream.ALL = field.NewAsterisk(tableName)
	_routeUpstream.ID = field.NewString(tableName, "id")
	_routeUpstream.RouteID = field.NewString(tableName, "route_id")
	_routeUpstream.UpstreamID = field.NewString(tableName, "upstream_id")
	_routeUpstream.Model = field.NewString(tableName, "model")
	_routeUpstream.Weight = field.NewInt32(tableName, "weight")
	_routeUpstream.Priority = field.NewInt32(tableName, "priority")
	_routeUpstream.Enabled = field.NewBool(tableName, "enabled")
	_routeUpstream.CreatedAt = field.NewString(tableName, "created_at")
	_routeUpstream.UpdatedAt = field.NewString(tableName, "updated_at")

	_routeUpstream.fillFieldMap()

	return _routeUpstream
}

type routeUpstream struct {
	routeUpstreamDo routeUpstreamDo

	ALL        field.Asterisk
	ID         field.String
	RouteID    field.String
	UpstreamID field.String
	Model      field.String
	Weight     field.Int32
	Priority   field.Int32
	Enabled    field.Bool
	CreatedAt  field.String
	UpdatedAt  field.String

	fieldMap map[string]field.Expr
}

func (r routeUpstream) Table(newTableName string) *routeUpstream {
	r.routeUpstreamDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r routeUpstream) As(alias string) *routeUpstream {
	r.routeUpstreamDo.DO = *(r.routeUpstreamDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *routeUpstream) updateTableName(table string) *routeUpstream {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewString(table, "id")
	r.RouteID = field.NewString(table, "route_id")
	r.UpstreamID = field.NewString(table, "upstream_id")
	r.Model = field.NewString(table, "model")
	r.Weight = field.NewInt32(table, "weight")
	r.Priority = field.NewInt32(table, "priority")
	r.Enabled = field.NewBool(table, "enabled")
	r.CreatedAt = field.NewString(table, "created_at")
	r.UpdatedAt = field.NewString(table, "updated_at")

	r.fillFieldMap()

	return r
}

func (r *routeUpstream) WithContext(ctx context.Context) IRouteUpstreamDo {
	return r.routeUpstreamDo.WithContext(ctx)
}

func (r routeUpstream) TableName() string { return r.routeUpstreamDo.TableName() }

func (r routeUpstream) Alias() string { return r.routeUpstreamDo.Alias() }

func (r routeUpstream) Columns(cols ...field.Expr) gen.Columns {
	return r.routeUpstreamDo.Columns(cols...)
}

func (r *routeUpstream) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *routeUpstream) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 9)
	r.fieldMap["id"] = r.ID
	r.fieldMap["route_id"] = r.RouteID
	r.fieldMap["upstream_id"] = r.UpstreamID
	r.fieldMap["model"] = r.Model
	r.fieldMap["weight"] = r.Weight
	r.fieldMap["priority"] = r.Priority
	r.fieldMap["enabled"] = r.Enabled
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
}

func (r routeUpstream) clone(db *gorm.DB) routeUpstream {
	r.routeUpstreamDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r routeUpstream) replaceDB(db *gorm.DB) routeUpstream {
	r.routeUpstreamDo.ReplaceDB(db)
	return r
}

type routeUpstreamDo struct{ gen.DO }

type IRouteUpstreamDo interface {
	gen.SubQuery
	Debug() IRouteUpstreamDo
	WithContext(ctx context.Context) IRouteUpstreamDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRouteUpstreamDo
	WriteDB() IRouteUpstreamDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRouteUpstreamDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRouteUpstreamDo
	Not(conds ...gen.Condition) IRouteUpstreamDo
	Or(conds ...gen.Condition) IRouteUpstreamDo
	Select(conds ...field.Expr) IRouteUpstreamDo
	Where(conds ...gen.Condition) IRouteUpstreamDo
	Order(conds ...field.Expr) IRouteUpstreamDo
	Distinct(cols ...field.Expr) IRouteUpstreamDo
	Omit(cols ...field.Expr) IRouteUpstreamDo
	Join(table schema.Tabler, on ...field.Expr) IRouteUpstreamDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRouteUpstreamDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRouteUpstreamDo
	Group(cols ...field.Expr) IRouteUpstreamDo
	Having(conds ...gen.Condition) IRouteUpstreamDo
	Limit(limit int) IRouteUpstreamDo
	Offset(offset int) IRouteUpstreamDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRouteUpstreamDo
	Unscoped() IRouteUpstreamDo
	Create(values ...*model.RouteUpstream) error
	CreateInBatches(values []*model.RouteUpstream, batchSize int) error
	Save(values ...*model.RouteUpstream) error
	First() (*model.RouteUpstream, error)
	Take() (*model.RouteUpstream, error)
	Last() (*model.RouteUpstream, error)
	Find() ([]*model.RouteUpstream, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RouteUpstream, err error)
	FindInBatches(result *[]*model.RouteUpstream, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RouteUpstream) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRouteUpstreamDo
	Assign(attrs ...field.AssignExpr) IRouteUpstreamDo
	Joins(fields ...field.RelationField) IRouteUpstreamDo
	Preload(fields ...field.RelationField) IRouteUpstreamDo
	FirstOrInit() (*model.RouteUpstream, error)
	FirstOrCreate() (*model.RouteUpstream, error)
	FindByPage(offset int, limit int) (result []*model.RouteUpstream, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRouteUpstreamDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r routeUpstreamDo) Debug() IRouteUpstreamDo {
	return r.withDO(r.DO.Debug())
}

func (r routeUpstreamDo) WithContext(ctx context.Context) IRouteUpstreamDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r routeUpstreamDo) ReadDB() IRouteUpstreamDo {
	return r.Clauses(dbresolver.Read)
}

func (r routeUpstreamDo) WriteDB() IRouteUpstreamDo {
	return r.Clauses(dbresolver.Write)
}

func (r routeUpstreamDo) Session(config *gorm.Session) IRouteUpstreamDo {
	return r.withDO(r.DO.Session(config))
}

func (r routeUpstreamDo) Clauses(conds ...clause.Expression) IRouteUpstreamDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r routeUpstreamDo) Returning(value interface{}, columns ...string) IRouteUpstreamDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r routeUpstreamDo) Not(conds ...gen.Condition) IRouteUpstreamDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r routeUpstreamDo) Or(conds ...gen.Condition) IRouteUpstreamDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r routeUpstreamDo) Select(conds ...field.Expr) IRouteUpstreamDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r routeUpstreamDo) Where(conds ...gen.Condition) IRouteUpstreamDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r routeUpstreamDo) Order(conds ...field.Expr) IRouteUpstreamDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r routeUpstreamDo) Distinct(cols ...field.Expr) IRouteUpstreamDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r routeUpstreamDo) Omit(cols ...field.Expr) IRouteUpstreamDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r routeUpstreamDo) Join(table schema.Tabler, on ...field.Expr) IRouteUpstreamDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r routeUpstreamDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRouteUpstreamDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r routeUpstreamDo) RightJoin(table schema.Tabler, on ...field.Expr) IRouteUpstreamDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r routeUpstreamDo) Group(cols ...field.Expr) IRouteUpstreamDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r routeUpstreamDo) Having(conds ...gen.Condition) IRouteUpstreamDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r routeUpstreamDo) Limit(limit int) IRouteUpstreamDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r routeUpstreamDo) Offset(offset int) IRouteUpstreamDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r routeUpstreamDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRouteUpstreamDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r routeUpstreamDo) Unscoped() IRouteUpstreamDo {
	return r.withDO(r.DO.Unscoped())
}

func (r routeUpstreamDo) Create(values ...*model.RouteUpstream) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r routeUpstreamDo) CreateInBatches(values []*model.RouteUpstream, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r routeUpstreamDo) Save(values ...*model.RouteUpstream) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r routeUpstreamDo) First() (*model.RouteUpstream, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouteUpstream), nil
	}
}

func (r routeUpstreamDo) Take() (*model.RouteUpstream, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouteUpstream), nil
	}
}

func (r routeUpstreamDo) Last() (*model.RouteUpstream, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouteUpstream), nil
	}
}

func (r routeUpstreamDo) Find() ([]*model.RouteUpstream, error) {
	result, err := r.DO.Find()
	return result.([]*model.RouteUpstream), err
}

func (r routeUpstreamDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RouteUpstream, err error) {
	buf := make([]*model.RouteUpstream, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r routeUpstreamDo) FindInBatches(result *[]*model.RouteUpstream, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r routeUpstreamDo) Attrs(attrs ...field.AssignExpr) IRouteUpstreamDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r routeUpstreamDo) Assign(attrs ...field.AssignExpr) IRouteUpstreamDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r routeUpstreamDo) Joins(fields ...field.RelationField) IRouteUpstreamDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r routeUpstreamDo) Preload(fields ...field.RelationField) IRouteUpstreamDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r routeUpstreamDo) FirstOrInit() (*model.RouteUpstream, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouteUpstream), nil
	}
}

func (r routeUpstreamDo) FirstOrCreate() (*model.RouteUpstream, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RouteUpstream), nil
	}
}

func (r routeUpstreamDo) FindByPage(offset int, limit int) (result []*model.RouteUpstream, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r routeUpstreamDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r routeUpstreamDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r routeUpstreamDo) Delete(models ...*model.RouteUpstream) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *routeUpstreamDo) withDO(do gen.Dao) *routeUpstreamDo {
	r.DO = *do.(*gen.DO)
	return r
}
